### ISSUE TITLE
Employer and Council Position

### ISSUE THREAD

**Issue by zumbak04** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#314]
**Describe your suggestion in full detail below:**
Anduin Lother should be a marshall of Stormwind, so far he's in random court.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/114318900-1a73fd80-9b20-11eb-990a-bb993f83e79e.png)

</details>

**Comment by zumbak04** [comment]
I expand this task, actually, we just adapt the employer and council setting from the CK2.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/114319954-b869c700-9b24-11eb-9420-e6fd0e69d39a.png)
![image](https://user-images.githubusercontent.com/46384992/114319980-d6cfc280-9b24-11eb-9ed5-60f825cd1d9c.png)

</details>
It will fix all issues related to this.

**Comment by LordEngineer** [comment]
employer setting works fine. It just has to be used during a date where the target is landed. The setting was in 556, Llane is unlanded until 565.

As for the other part, adapting the council setting I'm working on that but I might just replace it instead of making a dynamic script effect to replace it (which would cause a little more lag on load up anyway)
