### ISSUE TITLE
Ilidan not getting executed in prison

### ISSUE THREAD

**Issue by StarsPotato** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#561]
**Describe your suggestion in full detail below:**
As soon as she can Maev will execute Illidan, it would be nice if it didn't happen.

**Comment by Loralius** [comment]
Per discussions in discord, we can consider expanding this to encompass a Kaldorei aversion to executions. As we have seen, even high profile criminals to the Elunic faith such as Illidan and Xavius were only non-lethally neutralised (imprisoned for former, transformed into a log for latter) by the combined Sisterhood of Elune/Cenarion Circle government. Therefore, the fix for the Maiev-Illidan issue can potentially be expanded to encompass all `creature_night_elf` trait characters. This method would block the execution interaction from AI decisions if the criminals are Kaldorei and the decision-makers are Elunic.

Another approach would be to make executions criminal as a bonus doctrine group for the Elunic religion. Doing so still permits the AI to take the decision, but would in turn make them criminals and susceptible to being executed too.
