### ISSUE TITLE
Pygmy ethnicity

### ISSUE THREAD

**Issue by Grekopithikos** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#638]
**Describe your suggestion in full detail below:**
I think that Pygmies as an ethnicity would be one of the easiest to implement in the game, since pygmies basically look like short humans with some rough features(though I've seen that some of them have grey skin too).
![Pygmy_Pyramid](https://user-images.githubusercontent.com/70974452/131227837-f9c204b5-4ee5-44ec-bf1d-40f92ff01fd0.jpg)

**Comment by ercarp** [comment]
A pygmy ethnicity is planned, but I'm glad to hear there's at least someone asking about it since it doesn't seem like a popular one. I actually made a quick mock-up pygmy ethnicity recently to see how pygmy-ish we could get without custom blendshapes, but we may need to make some to give them bigger mouths (the screenshots below show the mouth width maxed out).

<details><summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/78575425/131228713-79a2b1f2-1a43-41cc-849a-7c27ea560e56.png)
![image](https://user-images.githubusercontent.com/78575425/131228719-d4d73345-e6e5-4f48-9e6f-3e718bae2d42.png)

</details>

**Comment by Grekopithikos** [comment]
So are they going to be static models like in #948  for now or not?

**Comment by ercarp** [comment]
> So are they going to be static models like in #948 for now or not?

I've left them for last because this is something I'm still debating on personally. They don't have any female models in WoW (all of them have facial hair at least) so right now I'm leaning toward creating a CK3 ethnicity instead of using static models for Pygmies.

I also want to add that while we are doing static models for a lot of races (and that may be disappointing to some), we hope to have proper CK3 ethnicities made for as many of them as possible down the line. But since our 3D team is fairly small and creating some of the less humanoid-looking races like Tauren is a much more involved and difficult process, it's good to have static models as placeholders we can fall back on.
