### ISSUE TITLE
Shenism faith should have their holy sites in Pandaria

### ISSUE THREAD

**Issue by Laetoy** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#793]
**Describe your suggestion in full detail below:**
Currently Shenism faith has holy sites all over the world, this feels quite off and holy sites should be more focused on their own continent. Throne of Thunder on the Isle of the Thunder King and Tu Shen Burial grounds in  the Vale of Eternal Blossoms seem like good choices for holy sites at least.

Admittedly Halls of Stone in Northrend is a good holy site, as that is where the Mogu were probably first created, but there still should be more than 1 holy site in Pandaria for them. Having Uldaman as a holy site seems weird, it's likely that no Mogu has even heard of the place before.

That's all.

**Comment by Loralius** [comment]
## Shenism Rework 
I agree with Laetoy.

Although the Mogu belong to the titanic religion group, they have long since forsaken and more importantly, forgotten their original charge, engaging instead feudal warring for untold millennia. Their present preoccupation is regaining dominion over Pandaria and selecting a clan to lead, in competing order. 

<details>
<summary> Shenism String </summary>

		thunder_king = {
			#Main Group
			color = rgb { 35 85 225 }
			icon = wcbb_thunder_king
			
			holy_site = tolnariv
			holy_site = red_desert
			holy_site = ulduar
			holy_site = nalaksha
			holy_site = dun_niffelem
			
			#Main Group
			doctrine = doctrine_pluralism_fundamentalist
			
			#Main Group
			doctrine = doctrine_concubines

			doctrine = tenet_pursuit_of_power
			doctrine = tenet_warmonger
			doctrine = tenet_progressivism

			holy_order_names = {
				{ name = "holy_order_servants_of_thunder" }
				{ name = "holy_order_chosen_of_ra" }
				{ name = "holy_order_gods_perfection" }
			}
		}
</details>

This propensity for conflict is already reflected in the tenets 'Pursuit of Power' and 'Warmonger'. **I futher propose that the tenent 'Progressivism' is replaced with another to better reflect contemporaenous Mogu culture. 'Cult of Strength' is one such candidate that is already defined.** 

<details> 
<summary> tenet_cult_of_strength </summary> 

		traits = {
			virtues = {
				physique_good
				strong
			}
			sins = {
				physique_bad
				weak
			}
		}

</details>

To bring the subject back to the topic, it follows that Shenic Holy Sites reflect present Mogu priorites/values instead of their ancient ones. 

**1) Keep Mogu'Shan Vaults (c_mogushan_vaults, k_zouchin)**
- Lei Shen knew about its purpose, power and usurped Ra'den here. 

**2) Add Mogu'Shan Palace (c_mogushan, k_mogushan)**
- Ancient imperial capital of the Mogu Empire seated in the Vale of Eternal Blossoms.
  - Provides character modifier bonus related to health.

**3) Add Throne of Thunder (c_lei_gong, k_lei_dao)**
- The Mogu may not know how to revive Lei Shen, but his island fortress is a symbol of power that boosts the prestige and legitimacy of any Mogu intent on becoming Emperor.
  - Provides character modifier bonus related to prestige, dynasty renown, opinion, acceptance or plot defense. 

### Bonus Event: [Reverse the Curse of Flesh](https://wowpedia.fandom.com/wiki/Titan_Runestone)
Controlling all holy sites (TBD if Lei Shen exclusive) will trigger a new event which allows Mogu to reverse the curse of flesh. In the lore it is said that the curse of flesh is brought on the mortal weaknesses such as greed, ambition, jealousy, etc that caused the Mogu to forsake their duty so this may need more discussion - but it's a cool idea!
Some possible effect ideas:
- Changes creature_mogu flag = titanforged_class
- Bestows nick_Will_of_the_Makers
- The cultural leader of the Mogu becomes the temporal head of Shenism for life.

**4) Add Heart of Fear (c_shekzeer, k_kyparqov)**
- This is not so much a holy site for the Mogu as much as an impetus for them to rid Pandaria of the Mantid threat once and for all in their conquest of Pandaria. No damned bugs will stand in the way of the Mogu's supremacy!
  - Taking this site can be likened to the pyschological milestone of Crusaders retaking Jerusalem or even controlling Mecca. 
  - Provides reachable but difficult goal once Mantid event chains, spawns and balancing are implemented; 
  - Provides Kyparite related benefits (needs discussion)

**5) ???**
There is an argument to slot in a titanic holy site because of their utter absence hithero - unless you include mogu'shan vaults. Their inclusion gives Shenic characters an incentive to expand beyond Pandaria. Indeed, a county within Un'goro would add another player into the game if the Qiraji snowball. 

Tolnariv (Halls of Origination) can also be kept on, but I'm not sure if Mogi would know about it or remember that it's any more significant than other Titanic facilities. I also noticed while looking through the files that the Tolnariv string is undefined.

The final option is to add a holy site in a Pandaren stronghold to symbolise, as with the Heart of Fear, the Mogu's complete mastership of the continent and the end of an era for the Pax Pandaria as it were.

## Add Shenism Heresy
Due to the complete divergence of Mogu Shenism from its original purpose, other titanic religions should consider it hostile. 

If another religion that is not hostile to titanic takes over Mogu'Shan Vaults (i.e. Sheli). Ra'den will be freed and will trigger a Shenism heresy as its spiritual head for life. This heresy will be considered righteous by other titanic faiths and be faithful to the original purpose of the titanforged.

**Comment by Loralius** [comment]
@Remerod Curious about your thoughts

**Comment by Remerod** [comment]
@Loralius i dunno about the curse of flesh, that's something that should be thought about in connecting of them getting a custom race/look models & tied to royal court reworks system somehow, so no opinion on that now

I like your views on how they should be pandaria centered only, but at the same time i like the titan focuses, for a normal Mogu your suggestion makes sense because they should be looked in pandaria with the mists, but Lei Shen is a character that have world domination on his agenda, since we currently don't know how we will do him i'm uncertain about the religious effect and more focused on how mogu would work and how Lei shen return would or would not alter that. the religion/faith should come after that.

**Comment by Loralius** [comment]
Good point. Let's wait and see how much the dynamics change with Royal Court before speculating on any large reworks. Whether or not it's Lei Shen commanding a revitalised Mogu Empire changes a lot too, as you say; perhaps setting 3 holy sites in Pandaria (MSV, MSP and ToT) and leaving the other two for other continents is a better sweet spot agnostic to whoever the Mogu ruler may be. Those other two holy sites can be determined at a later time, but in my opinion the first 3 are changes that can be implemented right now without significantly affecting any future design. (With placeholder effects subject to balancing)

**Comment by Loralius** [comment]
On [branch: shenism-holy-sites ](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/tree/shenism-holy-sites), replaced tenet_progressivism with tenet_cult of strength; added Mogu'Shan Palace and Throne of Thunder as holy sites. Both are currently inactive, pending character modifier ideas. Will think of something but suggestions welcome.
