### ISSUE TITLE
Give Bolvar Fordragon some land

### ISSUE THREAD

**Issue by ercarp** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#813]
**Describe your suggestion in full detail below:**
Just as we [gave land to all of the Mograines](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/issues/628) to make them playable, I think we should do the same with **Bolvar Fordragon** for players who would like to play as him. Fordragon is kind of a big name so I think it would make sense for him to be landed anyway.

[According to Wowpedia](https://wowpedia.fandom.com/wiki/Bolvar_Fordragon), he isn't known for being associated with being the ruler of any particular location, except Fordragon Hold in Northrend, but as far as I know that won't exist until Wrath of the Lich King.

Given that he's the regent of Stormwind during Varian's absence, I think giving him a single county or a small duchy somewhere near Stormwind would be acceptable.

**Comment by Remerod** [comment]
Since Bolwar was a paladin wouldn't he been part of a (paladin) holy order though? 

But i guess this implies that their linage are from Stormwind
https://wowpedia.fandom.com/wiki/Lady_Mara_Fordragon

( i think Mara should be his mommy)

So they should be part of a Stormwindian nobility at least i think.

Since there is no real place tied to them or hinting at that, perhaps they could have something near duskwood or redridge mountain, since those are pretty backwater anyway?

**Comment by pedromdpereira** [comment]
Hello! 
Do you agree with Azora?
![image](https://user-images.githubusercontent.com/35965798/149593634-bf266682-9d17-4312-936c-de2960627cbf.png)

It stays as Stormwind vassal across all start dates, it's near and hasn't any true ruler atm from what I read.
